### ISSUE TITLE
ho to pass arguments to surm-submit.py

### ISSUE THREAD

**Issue by SilasK** [Snakemake-Profiles/slurm#7]
I've seen you wrote a long list of arguments which can be given to the slurm-submit.py or torque-submit.py how can I pass them to the script?

I tried in the config.yaml
time:600

and it passed the 600 as target to the snakefile, which search for the file.

**Comment by boulund** [comment]
I don't know exactly how the original authors intended this to work, but I modified the `cluster:` line in `config.yaml` to this:

```
cluster: "path/to/slurm-submit.py --account {cluster.account} --partition {cluster.partition} --ntasks {cluster.n} --time {cluster.time} --error {cluster.stderr} --output {cluster.stdout} --job-name '{cluster.jobname}'"
```
Notice that the path to `slurm-submit.py` must be relative to the workdir you are calling snakemake from (in my case I put these in a folder called `cluster_configs/slurm` inside my Snakemake workdir).
This of course requires that all these cluster options are set somehow. It can be done with a `--cluster-config` file (which can also be specified with `cluster-config:` inside `config.yaml`):

```
__default__: 
    account: "<account_name>"
    partition: "<partition_name>"
    extra: ""
    time: "00:15:00"
    n: 2
    stderr: "slurm_logs/slurm-{rule}.{wildcards}.stderr"
    stdout: "slurm_logs/slurm-{rule}.{wildcards}.stdout"
    jobname: "StaG: {rule} {wildcards}"
```
